const board1 = [
    {
      id: 1,
      light: false,
      lit: false,
      number: true,
      black: true,
      value: 25,
    },
    {
      id: 2,
      light: false,
      lit: false,
      number: false,
      black: false,
      value: null,
    },
    {
      id: 3,
      light: false,
      lit: false,
      number: false,
      black: false,
      value: null,
    },
    {
      id: 4,
      light: false,
      lit: false,
      number: false,
      black: false,
      value: null,
    },
    {
      id: 5,
      light: false,
      lit: false,
      number: false,
      black: false,
      value: null,
    },
    {
      id: 6,
      light: false,
      lit: false,
      number: false,
      black: true,
      value: null,
    },
    {
      id: 7,
      light: true,
      lit: false,
      number: true,
      black: false,
      value: 0,
    },
    {
      id: 8,
      light: false,
      lit: false,
      number: false,
      black: true,
      value: null,
    },
    {
      id: 9,
      light: false,
      lit: false,
      number: false,
      black: false,
      value: null,
    },
    {
      id: 10,
      light: false,
      lit: false,
      number: false,
      black: false,
      value: null,
    },
    {
      id: 11,
      light: false,
      lit: false,
      number: false,
      black: false,
      value: null,
    },
    {
      id: 12,
      light: false,
      lit: false,
      number: false,
      black: false,
      value: null,
    },
    {
      id: 13,
      light: false,
      lit: false,
      number: false,
      black: false,
      value: null,
    },
    {
      id: 14,
      light: false,
      lit: false,
      number: false,
      black: false,
      value: null,
    },
    {
      id: 15,
      light: false,
      lit: false,
      number: false,
      black: false,
      value: null,
    },
    {
      id: 16,
      light: false,
      lit: false,
      number: false,
      black: false,
      value: null,
    },
    {
      id: 17,
      light: false,
      lit: false,
      number: false,
      black: false,
      value: null,
    },
    {
      id: 18,
      light: false,
      lit: false,
      number: false,
      black: false,
      value: null,
    },
    {
      id: 19,
      light: false,
      lit: false,
      number: false,
      black: false,
      value: null,
    },
    {
      id: 20,
      light: false,
      lit: false,
      number: false,
      black: false,
      value: null,
    },
    {
      id: 21,
      light: false,
      lit: false,
      number: false,
      black: false,
      value: 5,
    },
    {
      id: 22,
      light: false,
      lit: false,
      number: false,
      black: false,
      value: null,
    },
    {
      id: 23,
      light: false,
      lit: false,
      number: false,
      black: false,
      value: null,
    },
    {
      id: 24,
      light: false,
      lit: false,
      number: false,
      black: false,
      value: null,
    },
    {
      id: 25,
      light: false,
      lit: false,
      number: true,
      black: false,
      value: 4,
    },
    {
      id: 26,
      light: false,
      lit: false,
      number: false,
      black: false,
      value: null,
    },
    {
      id: 27,
      light: false,
      lit: false,
      number: false,
      black: false,
      value: null,
    },
    {
      id: 28,
      light: false,
      lit: false,
      number: false,
      black: false,
      value: null,
    },
    {
      id: 29,
      light: false,
      lit: false,
      number: false,
      black: false,
      value: null,
    },
    {
      id: 30,
      light: false,
      lit: false,
      number: false,
      black: false,
      value: null,
    },
    {
      id: 31,
      light: false,
      lit: false,
      number: false,
      black: false,
      value: null,
    },
    {
      id: 32,
      light: false,
      lit: false,
      number: false,
      black: false,
      value: null,
    },
    {
      id: 33,
      light: false,
      lit: false,
      number: false,
      black: false,
      value: null,
    },
    {
      id: 34,
      light: false,
      lit: false,
      number: false,
      black: false,
      value: null,
    },
    {
      id: 35,
      light: false,
      lit: false,
      number: false,
      black: false,
      value: null,
    },
    {
      id: 36,
      light: false,
      lit: false,
      number: false,
      black: false,
      value: null,
    },
    {
      id: 37,
      light: false,
      lit: false,
      number: false,
      black: false,
      value: null,
    },
    {
      id: 38,
      light: false,
      lit: false,
      number: false,
      black: false,
      value: null,
    },
    {
      id: 39,
      light: false,
      lit: false,
      number: false,
      black: false,
      value: null,
    },
    {
      id: 40,
      light: false,
      lit: false,
      number: false,
      black: false,
      value: null,
    },
    {
      id: 41,
      light: false,
      lit: false,
      number: false,
      black: false,
      value: null,
    },
    {
      id: 42,
      light: false,
      lit: false,
      number: true,
      black: true,
      value: 1,
    },
    {
      id: 43,
      light: false,
      lit: false,
      number: false,
      black: true,
      value: null,
    },
    {
      id: 44,
      light: false,
      lit: false,
      number: false,
      black: true,
      value: null,
    },
    {
      id: 45,
      light: false,
      lit: false,
      number: false,
      black: false,
      value: null,
    },
    {
      id: 46,
      light: false,
      lit: false,
      number: false,
      black: false,
      value: null,
    },
    {
      id: 47,
      light: false,
      lit: false,
      number: false,
      black: false,
      value: null,
    },
    {
      id: 48,
      light: false,
      lit: false,
      number: false,
      black: false,
      value: null,
    },
    {
      id: 49,
      light: true,
      lit: false,
      number: false,
      black: true,
      value: null,
    }
  ]

export default board1;